// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJTL-KnA0owQeKuq63NiHs0tRZJgwAu8Y',
    appId: '1:1071584442702:android:430f3322823e87495f861f',
    messagingSenderId: '1071584442702',
    projectId: 'healthy-san',
    storageBucket: 'healthy-san.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBouTN9SWmimxWSLH6Jmasr5fi_wf_QQU',
    appId: '1:1071584442702:ios:b9a380105119ddb15f861f',
    messagingSenderId: '1071584442702',
    projectId: 'healthy-san',
    storageBucket: 'healthy-san.appspot.com',
    iosClientId: '1071584442702-e766lbapfagdc5tnemgffc0dfqb9ptgb.apps.googleusercontent.com',
    iosBundleId: 'com.healthy-san.app',
  );
}
